#DataSource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_ssm?useSSL=false
    username: root
    password: 1111

#设置项目名
server:
  servlet:
    context-path: /springboot_ssm

#mybatis
mybatis-plus:
   mapper-locations: classpath*:/modules/mapper/**Mapper.xml
   typeAliasesPackage: com.example.cms.modules.entity